/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppCompetitorsRouteImport } from './routes/app.competitors'
import { Route as AppMentionsRouteImport } from './routes/app.mentions'
import { Route as AppOptimizeRouteImport } from './routes/app.optimize'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppResearchRouteImport } from './routes/app.research'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as AppAuditIdRouteImport } from './routes/app.audit.$id'
import { Route as AppProjectIdRouteImport } from './routes/app.project.$id'
import { Route as ApiPublicCronAutoAuditRouteImport } from './routes/api/public/cron/auto-audit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppCompetitorsRoute = AppCompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => AppRoute,
} as any)
const AppMentionsRoute = AppMentionsRouteImport.update({
  id: '/mentions',
  path: '/mentions',
  getParentRoute: () => AppRoute,
} as any)
const AppOptimizeRoute = AppOptimizeRouteImport.update({
  id: '/optimize',
  path: '/optimize',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppResearchRoute = AppResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AppRoute,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuditIdRoute = AppAuditIdRouteImport.update({
  id: '/audit/$id',
  path: '/audit/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectIdRoute = AppProjectIdRouteImport.update({
  id: '/project/$id',
  path: '/project/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicCronAutoAuditRoute = ApiPublicCronAutoAuditRouteImport.update({
  id: '/api/public/cron/auto-audit',
  path: '/api/public/cron/auto-audit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/admin': typeof AppAdminRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/competitors': typeof AppCompetitorsRoute
  '/app/mentions': typeof AppMentionsRoute
  '/app/optimize': typeof AppOptimizeRoute
  '/app/reports': typeof AppReportsRoute
  '/app/research': typeof AppResearchRoute
  '/r/$token': typeof RTokenRoute
  '/app/': typeof AppIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/app/audit/$id': typeof AppAuditIdRoute
  '/app/project/$id': typeof AppProjectIdRoute
  '/api/public/cron/auto-audit': typeof ApiPublicCronAutoAuditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/admin': typeof AppAdminRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/competitors': typeof AppCompetitorsRoute
  '/app/mentions': typeof AppMentionsRoute
  '/app/optimize': typeof AppOptimizeRoute
  '/app/reports': typeof AppReportsRoute
  '/app/research': typeof AppResearchRoute
  '/r/$token': typeof RTokenRoute
  '/app': typeof AppIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/app/audit/$id': typeof AppAuditIdRoute
  '/app/project/$id': typeof AppProjectIdRoute
  '/api/public/cron/auto-audit': typeof ApiPublicCronAutoAuditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/admin': typeof AppAdminRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/competitors': typeof AppCompetitorsRoute
  '/app/mentions': typeof AppMentionsRoute
  '/app/optimize': typeof AppOptimizeRoute
  '/app/reports': typeof AppReportsRoute
  '/app/research': typeof AppResearchRoute
  '/r/$token': typeof RTokenRoute
  '/app/': typeof AppIndexRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/app/audit/$id': typeof AppAuditIdRoute
  '/app/project/$id': typeof AppProjectIdRoute
  '/api/public/cron/auto-audit': typeof ApiPublicCronAutoAuditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/admin'
    | '/app/alerts'
    | '/app/billing'
    | '/app/competitors'
    | '/app/mentions'
    | '/app/optimize'
    | '/app/reports'
    | '/app/research'
    | '/r/$token'
    | '/app/'
    | '/api/public/stripe-webhook'
    | '/app/audit/$id'
    | '/app/project/$id'
    | '/api/public/cron/auto-audit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/admin'
    | '/app/alerts'
    | '/app/billing'
    | '/app/competitors'
    | '/app/mentions'
    | '/app/optimize'
    | '/app/reports'
    | '/app/research'
    | '/r/$token'
    | '/app'
    | '/api/public/stripe-webhook'
    | '/app/audit/$id'
    | '/app/project/$id'
    | '/api/public/cron/auto-audit'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/admin'
    | '/app/alerts'
    | '/app/billing'
    | '/app/competitors'
    | '/app/mentions'
    | '/app/optimize'
    | '/app/reports'
    | '/app/research'
    | '/r/$token'
    | '/app/'
    | '/api/public/stripe-webhook'
    | '/app/audit/$id'
    | '/app/project/$id'
    | '/api/public/cron/auto-audit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  RTokenRoute: typeof RTokenRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  ApiPublicCronAutoAuditRoute: typeof ApiPublicCronAutoAuditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/competitors': {
      id: '/app/competitors'
      path: '/competitors'
      fullPath: '/app/competitors'
      preLoaderRoute: typeof AppCompetitorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mentions': {
      id: '/app/mentions'
      path: '/mentions'
      fullPath: '/app/mentions'
      preLoaderRoute: typeof AppMentionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/optimize': {
      id: '/app/optimize'
      path: '/optimize'
      fullPath: '/app/optimize'
      preLoaderRoute: typeof AppOptimizeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/research': {
      id: '/app/research'
      path: '/research'
      fullPath: '/app/research'
      preLoaderRoute: typeof AppResearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/audit/$id': {
      id: '/app/audit/$id'
      path: '/audit/$id'
      fullPath: '/app/audit/$id'
      preLoaderRoute: typeof AppAuditIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/project/$id': {
      id: '/app/project/$id'
      path: '/project/$id'
      fullPath: '/app/project/$id'
      preLoaderRoute: typeof AppProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/cron/auto-audit': {
      id: '/api/public/cron/auto-audit'
      path: '/api/public/cron/auto-audit'
      fullPath: '/api/public/cron/auto-audit'
      preLoaderRoute: typeof ApiPublicCronAutoAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAlertsRoute: typeof AppAlertsRoute
  AppBillingRoute: typeof AppBillingRoute
  AppCompetitorsRoute: typeof AppCompetitorsRoute
  AppMentionsRoute: typeof AppMentionsRoute
  AppOptimizeRoute: typeof AppOptimizeRoute
  AppReportsRoute: typeof AppReportsRoute
  AppResearchRoute: typeof AppResearchRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAuditIdRoute: typeof AppAuditIdRoute
  AppProjectIdRoute: typeof AppProjectIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAlertsRoute: AppAlertsRoute,
  AppBillingRoute: AppBillingRoute,
  AppCompetitorsRoute: AppCompetitorsRoute,
  AppMentionsRoute: AppMentionsRoute,
  AppOptimizeRoute: AppOptimizeRoute,
  AppReportsRoute: AppReportsRoute,
  AppResearchRoute: AppResearchRoute,
  AppIndexRoute: AppIndexRoute,
  AppAuditIdRoute: AppAuditIdRoute,
  AppProjectIdRoute: AppProjectIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  RTokenRoute: RTokenRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  ApiPublicCronAutoAuditRoute: ApiPublicCronAutoAuditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
