/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppMentionsRouteImport } from './routes/app.mentions'
import { Route as AppOptimizeRouteImport } from './routes/app.optimize'
import { Route as AppAuditIdRouteImport } from './routes/app.audit.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMentionsRoute = AppMentionsRouteImport.update({
  id: '/mentions',
  path: '/mentions',
  getParentRoute: () => AppRoute,
} as any)
const AppOptimizeRoute = AppOptimizeRouteImport.update({
  id: '/optimize',
  path: '/optimize',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditIdRoute = AppAuditIdRouteImport.update({
  id: '/audit/$id',
  path: '/audit/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/mentions': typeof AppMentionsRoute
  '/app/optimize': typeof AppOptimizeRoute
  '/app/': typeof AppIndexRoute
  '/app/audit/$id': typeof AppAuditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/mentions': typeof AppMentionsRoute
  '/app/optimize': typeof AppOptimizeRoute
  '/app': typeof AppIndexRoute
  '/app/audit/$id': typeof AppAuditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/mentions': typeof AppMentionsRoute
  '/app/optimize': typeof AppOptimizeRoute
  '/app/': typeof AppIndexRoute
  '/app/audit/$id': typeof AppAuditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/mentions'
    | '/app/optimize'
    | '/app/'
    | '/app/audit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/mentions'
    | '/app/optimize'
    | '/app'
    | '/app/audit/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/mentions'
    | '/app/optimize'
    | '/app/'
    | '/app/audit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mentions': {
      id: '/app/mentions'
      path: '/mentions'
      fullPath: '/app/mentions'
      preLoaderRoute: typeof AppMentionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/optimize': {
      id: '/app/optimize'
      path: '/optimize'
      fullPath: '/app/optimize'
      preLoaderRoute: typeof AppOptimizeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit/$id': {
      id: '/app/audit/$id'
      path: '/audit/$id'
      fullPath: '/app/audit/$id'
      preLoaderRoute: typeof AppAuditIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppMentionsRoute: typeof AppMentionsRoute
  AppOptimizeRoute: typeof AppOptimizeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAuditIdRoute: typeof AppAuditIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppMentionsRoute: AppMentionsRoute,
  AppOptimizeRoute: AppOptimizeRoute,
  AppIndexRoute: AppIndexRoute,
  AppAuditIdRoute: AppAuditIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
